### ISSUE TITLE
Appene kan ikke nedlastes med ikke-norsk Apple ID

### ISSUE THREAD

**Issue by BorBorBor** [folkehelseinstituttet/Fhi.Koronasertifikat.Verifikasjon.App#66]
Akkurat nå så kan både Helsenorge-appen og Kontroll av koronasertifikat-appen ikke installeres for de uten norsk Apple-konto. Dermed er koronasertifikatappene ikke brukbart for de som har flytta til Norge men som har Apple-konto fra før — selv om de har fødselsnummer, bankid, norsk telefonnummer osv. Det å bytte land på Apple ID er en slitsom prosedyre som helst unngås, og det pleier ikke å være nødvendig, de fleste europeiske appene er tilgjengelig i de ulike butikkene uten problemer.

Det er altså veldig enkelt å rette opp det her problemet, bare å endre innstillingene i iTunes Connect.

**Comment by lisaFHI** [comment]
Hei. Du kan logge deg på helsenorge.no via nettleser og skrive ut koronasertifikatet derfra. Skal i tillegg se om helsenorge appen kan legges litt mer åpent. Kontroll-appen skal kun benyttes til kontroll, så denne trenger du ikke.

**Comment by lisaFHI** [comment]
Det er mulig å laste ned PDF til mobilen, så du slipper å logge på underveis. Men uansett - jeg ser poenget ditt og har allerede tatt det opp med Norsk Helsenett.

**Comment by kjetillvl** [comment]
Hei

Takk for tilbakemelding og at du gjør oss klar over denne. Vi har nå åpnet opp for Helsenorge i App store og Google Play.

**Comment by BorBorBor** [comment]
Det er konge! Tusen takk :)

**Comment by lisaFHI** [comment]
Kan du prøve via direktelink: 

Android: https://play.google.com/store/apps/details?id=direktoratetforehelse.helsenorge.no
iOS: https://apps.apple.com/no/app/helsenorge-no/id1108860468

**Comment by BorBorBor** [comment]
@lisaFHI Den funker, dere har løst problemet med Helsenorge-appen, men "Kontrol av koronasertifikat" er fremdeles utilgjengelig.

**Comment by lisaFHI** [comment]
Søren, feil linker ja. Beklager. Må lete litt etter korrekte linker.

**Comment by lisaFHI** [comment]
https://play.google.com/store/apps/details?id=no.fhi.KoronasertifikatKontrollapp&hl=en_US&gl=NO
eller
https://apps.apple.com/no/app/kontroll-av-koronasertifikat/id1568677698

**Comment by BorBorBor** [comment]
På iOS får jeg "Denne appen er ikke tilgjengelig i ditt land eller område".

**Comment by lisaFHI** [comment]
Prøv igjen nå. Skal være åpen nå.

**Comment by BorBorBor** [comment]
Samme feilmelding…
